language: swift
os: osx
osx_image: xcode9
before_install:
  - gem install xcpretty
  - gem install jazzy
script:
  - xcodebuild -workspace ReRxSwift.xcworkspace -scheme AllTests test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0'|xcpretty
  - jazzy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
