language: swift
os: osx
osx_image: xcode9
before_install:
  - brew install xcpretty
script: 
  - xcodebuild -workspace ReRxSwift.xcworkspace -scheme AllTests test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0'|xcpretty
